#!/bin/bash
#set -e # fail on any error
#set -u # treat unset variables as errors

# ======[ Trap Errors ]======#
#set -E # let shell functions inherit ERR trap

# Trap non-normal exit signals:
# 1/HUP, 2/INT, 3/QUIT, 15/TERM, ERR
#trap err_handler 1 2 3 15 ERR
#function err_handler {
#	local exit_status=${1:-$?}
#	exit $exit_status
#}

case $1 in
    configure)
	nginx -t
	RET=$?

	if [ $RET != 0 ]
	then
	    echo "Error in config for nginx"
	    exit 1
	fi

	systemctl reload nginx
	;;
    *)
	;;
esac
